---
# tasks file for tomcat-role
- include_tasks: update.yml
- include_tasks: java.yml
- include_tasks: user.yml
- include_tasks: install-tomcat.yml
- include_tasks: extract.yml
- include_tasks: update-permissions.yml
