---
- name: create group
  group:
    name: tomcat
    state: present

- name: create user
  user:
    name: tomcat
    comment: this is user tomcat
    shell: /bin/false
    group: tomcat
    home: /opt/tomcat    