---
- name: install java
  hosts: webserver
  become: yes
  gather_facts: no
  tasks:
  - name: install java on server
    apt:
      name: apache2
      state: present
  - name: change the html page
    template:
      src: index.j2
      dest: /var/www/html/index.j2
  - name: restart the server
    service:
      name: apache2
      state: restarted      
